blank_issues_enabled: true
contact_links:
  - name: AlgoScope Discussions via GitHub Issues
    url: https://github.com/algoscope-hq/AlgoScope/issues
    about: Use issues for bugs, ideas, and project discussion.